---
- hosts: rnb
  become: True
  tasks:
        
    - name: Run docker container
      command: "docker stop raam043/myapp-project"
      command: "docker rm -f raam043/myapp-project"
      command: "docker image rm -f raam043/myapp-project"
      
    - name: Run docker container
      docker_container:
        name: WebServer
        image: raam043/myapp-project
        state: started
        exposed_ports:
        - "80"
        ports:
        - "80:80"
